### ISSUE TITLE
编辑器输出有误

### ISSUE THREAD

**Issue by TinkerDeng** [youzan/show-me-the-code#2]
var x = 1;
function foo(x, y = function() { x = 2; }) {
  var x = 3;
  y();
  console.log(x);
}

foo() // 应该输出3，编辑器输出2

![image](https://user-images.githubusercontent.com/18025615/50468204-82e75100-09e1-11e9-8615-51e737a37ffd.png)

**Comment by intellild** [comment]
目前的执行会经过babel，确实会存在这个问题

**Comment by intellild** [comment]
现在运行代码不会经过babel了
